version: '3'
services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    env_file: .env
    ports:
      - 3306:3306
    environment:
      - JWT_KEY=${JWT_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - BASE_PORT=${BASE_PORT}
      - SERVER_URL=${SERVER_URL}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=duyhaiserver
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - node-networks

  app:
    depends_on:
      - mysql_db
    build: .
    container_name: const-node 
    env_file: .env
    ports:
      - 8080:8080
    environment:
      - JWT_KEY=${JWT_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - BASE_PORT=${BASE_PORT}
      - SERVER_URL=${SERVER_URL}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    networks:
      - node-networks

volumes:
  mysql_db:
    driver: local

networks:
  node-networks:
