JWT_KEY=professionalDEV
SERVER_URL=https://haitratanserver.click
BASE_PORT=8080
SENDGRID_API_KEY=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
DATABASE_URL=mysql://root:admin@localhost:3306/duyhaiserver?schema=public